name: travelapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  flutter_swiper: ^1.1.6
  get: 4.6.1
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/airport.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
